// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat_grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Room struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId               int64                `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Room) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *Room) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Room) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Member struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId               int64                `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int64                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Member) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Member) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Member) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Member) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Message struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string               `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	RoomId               int64                `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Message) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Message) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Message) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Message) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateRoomReq struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomReq) Reset()         { *m = CreateRoomReq{} }
func (m *CreateRoomReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoomReq) ProtoMessage()    {}
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *CreateRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomReq.Unmarshal(m, b)
}
func (m *CreateRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomReq.Marshal(b, m, deterministic)
}
func (m *CreateRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomReq.Merge(m, src)
}
func (m *CreateRoomReq) XXX_Size() int {
	return xxx_messageInfo_CreateRoomReq.Size(m)
}
func (m *CreateRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomReq proto.InternalMessageInfo

func (m *CreateRoomReq) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *CreateRoomReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetRoomReq struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoomReq) Reset()         { *m = GetRoomReq{} }
func (m *GetRoomReq) String() string { return proto.CompactTextString(m) }
func (*GetRoomReq) ProtoMessage()    {}
func (*GetRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *GetRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomReq.Unmarshal(m, b)
}
func (m *GetRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomReq.Marshal(b, m, deterministic)
}
func (m *GetRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomReq.Merge(m, src)
}
func (m *GetRoomReq) XXX_Size() int {
	return xxx_messageInfo_GetRoomReq.Size(m)
}
func (m *GetRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomReq proto.InternalMessageInfo

func (m *GetRoomReq) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *GetRoomReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListMembersReq struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersReq) Reset()         { *m = ListMembersReq{} }
func (m *ListMembersReq) String() string { return proto.CompactTextString(m) }
func (*ListMembersReq) ProtoMessage()    {}
func (*ListMembersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *ListMembersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersReq.Unmarshal(m, b)
}
func (m *ListMembersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersReq.Marshal(b, m, deterministic)
}
func (m *ListMembersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersReq.Merge(m, src)
}
func (m *ListMembersReq) XXX_Size() int {
	return xxx_messageInfo_ListMembersReq.Size(m)
}
func (m *ListMembersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersReq proto.InternalMessageInfo

func (m *ListMembersReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *ListMembersReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListMembersRes struct {
	Members              []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListMembersRes) Reset()         { *m = ListMembersRes{} }
func (m *ListMembersRes) String() string { return proto.CompactTextString(m) }
func (*ListMembersRes) ProtoMessage()    {}
func (*ListMembersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *ListMembersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersRes.Unmarshal(m, b)
}
func (m *ListMembersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersRes.Marshal(b, m, deterministic)
}
func (m *ListMembersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersRes.Merge(m, src)
}
func (m *ListMembersRes) XXX_Size() int {
	return xxx_messageInfo_ListMembersRes.Size(m)
}
func (m *ListMembersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersRes proto.InternalMessageInfo

func (m *ListMembersRes) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type CreateMemberReq struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMemberReq) Reset()         { *m = CreateMemberReq{} }
func (m *CreateMemberReq) String() string { return proto.CompactTextString(m) }
func (*CreateMemberReq) ProtoMessage()    {}
func (*CreateMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *CreateMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMemberReq.Unmarshal(m, b)
}
func (m *CreateMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMemberReq.Marshal(b, m, deterministic)
}
func (m *CreateMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMemberReq.Merge(m, src)
}
func (m *CreateMemberReq) XXX_Size() int {
	return xxx_messageInfo_CreateMemberReq.Size(m)
}
func (m *CreateMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMemberReq proto.InternalMessageInfo

func (m *CreateMemberReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *CreateMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteMemberReq struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMemberReq) Reset()         { *m = DeleteMemberReq{} }
func (m *DeleteMemberReq) String() string { return proto.CompactTextString(m) }
func (*DeleteMemberReq) ProtoMessage()    {}
func (*DeleteMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{8}
}

func (m *DeleteMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMemberReq.Unmarshal(m, b)
}
func (m *DeleteMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMemberReq.Marshal(b, m, deterministic)
}
func (m *DeleteMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMemberReq.Merge(m, src)
}
func (m *DeleteMemberReq) XXX_Size() int {
	return xxx_messageInfo_DeleteMemberReq.Size(m)
}
func (m *DeleteMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMemberReq proto.InternalMessageInfo

func (m *DeleteMemberReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *DeleteMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateMessageReq struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	RoomId               int64    `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageReq) Reset()         { *m = CreateMessageReq{} }
func (m *CreateMessageReq) String() string { return proto.CompactTextString(m) }
func (*CreateMessageReq) ProtoMessage()    {}
func (*CreateMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{9}
}

func (m *CreateMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageReq.Unmarshal(m, b)
}
func (m *CreateMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageReq.Marshal(b, m, deterministic)
}
func (m *CreateMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageReq.Merge(m, src)
}
func (m *CreateMessageReq) XXX_Size() int {
	return xxx_messageInfo_CreateMessageReq.Size(m)
}
func (m *CreateMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageReq proto.InternalMessageInfo

func (m *CreateMessageReq) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateMessageReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *CreateMessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListMessagesReq struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMessagesReq) Reset()         { *m = ListMessagesReq{} }
func (m *ListMessagesReq) String() string { return proto.CompactTextString(m) }
func (*ListMessagesReq) ProtoMessage()    {}
func (*ListMessagesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{10}
}

func (m *ListMessagesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessagesReq.Unmarshal(m, b)
}
func (m *ListMessagesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessagesReq.Marshal(b, m, deterministic)
}
func (m *ListMessagesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessagesReq.Merge(m, src)
}
func (m *ListMessagesReq) XXX_Size() int {
	return xxx_messageInfo_ListMessagesReq.Size(m)
}
func (m *ListMessagesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessagesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessagesReq proto.InternalMessageInfo

func (m *ListMessagesReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *ListMessagesReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListMessagesRes struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListMessagesRes) Reset()         { *m = ListMessagesRes{} }
func (m *ListMessagesRes) String() string { return proto.CompactTextString(m) }
func (*ListMessagesRes) ProtoMessage()    {}
func (*ListMessagesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{11}
}

func (m *ListMessagesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessagesRes.Unmarshal(m, b)
}
func (m *ListMessagesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessagesRes.Marshal(b, m, deterministic)
}
func (m *ListMessagesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessagesRes.Merge(m, src)
}
func (m *ListMessagesRes) XXX_Size() int {
	return xxx_messageInfo_ListMessagesRes.Size(m)
}
func (m *ListMessagesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessagesRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessagesRes proto.InternalMessageInfo

func (m *ListMessagesRes) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type StreamMessageReq struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMessageReq) Reset()         { *m = StreamMessageReq{} }
func (m *StreamMessageReq) String() string { return proto.CompactTextString(m) }
func (*StreamMessageReq) ProtoMessage()    {}
func (*StreamMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{12}
}

func (m *StreamMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMessageReq.Unmarshal(m, b)
}
func (m *StreamMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMessageReq.Marshal(b, m, deterministic)
}
func (m *StreamMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMessageReq.Merge(m, src)
}
func (m *StreamMessageReq) XXX_Size() int {
	return xxx_messageInfo_StreamMessageReq.Size(m)
}
func (m *StreamMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMessageReq proto.InternalMessageInfo

func (m *StreamMessageReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *StreamMessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*Room)(nil), "chat_grpc.Room")
	proto.RegisterType((*Member)(nil), "chat_grpc.Member")
	proto.RegisterType((*Message)(nil), "chat_grpc.Message")
	proto.RegisterType((*CreateRoomReq)(nil), "chat_grpc.CreateRoomReq")
	proto.RegisterType((*GetRoomReq)(nil), "chat_grpc.GetRoomReq")
	proto.RegisterType((*ListMembersReq)(nil), "chat_grpc.ListMembersReq")
	proto.RegisterType((*ListMembersRes)(nil), "chat_grpc.ListMembersRes")
	proto.RegisterType((*CreateMemberReq)(nil), "chat_grpc.CreateMemberReq")
	proto.RegisterType((*DeleteMemberReq)(nil), "chat_grpc.DeleteMemberReq")
	proto.RegisterType((*CreateMessageReq)(nil), "chat_grpc.CreateMessageReq")
	proto.RegisterType((*ListMessagesReq)(nil), "chat_grpc.ListMessagesReq")
	proto.RegisterType((*ListMessagesRes)(nil), "chat_grpc.ListMessagesRes")
	proto.RegisterType((*StreamMessageReq)(nil), "chat_grpc.StreamMessageReq")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x6e, 0xda, 0x3e,
	0x14, 0x96, 0x49, 0x0a, 0x3f, 0x0e, 0xb4, 0xf4, 0x67, 0x69, 0x2b, 0x73, 0x2f, 0x16, 0xe5, 0x0a,
	0x69, 0x52, 0xd8, 0xd8, 0xc5, 0xb4, 0x8b, 0x4a, 0x03, 0xf6, 0x47, 0x95, 0x56, 0x69, 0x0a, 0xed,
	0x6e, 0x51, 0x20, 0x1e, 0xcd, 0x44, 0xe4, 0x2c, 0x36, 0x95, 0xfa, 0x14, 0x7b, 0x8a, 0xbd, 0xc7,
	0x5e, 0x62, 0x2f, 0xb3, 0xab, 0x29, 0x76, 0x0c, 0x4e, 0x02, 0xad, 0x5a, 0x71, 0x97, 0xc3, 0x77,
	0xfc, 0xf9, 0x7c, 0xe7, 0x7c, 0xc7, 0x00, 0xcc, 0xaf, 0x03, 0xe1, 0x25, 0x29, 0x13, 0x0c, 0x37,
	0xb3, 0xef, 0xe9, 0x22, 0x4d, 0xe6, 0xe4, 0xe4, 0x26, 0x58, 0x46, 0x61, 0x20, 0x68, 0x5f, 0x7f,
	0xa8, 0x1c, 0x72, 0xba, 0x60, 0x6c, 0xb1, 0xa4, 0x7d, 0x19, 0xcd, 0x56, 0xdf, 0xfa, 0x34, 0x4e,
	0xc4, 0x6d, 0x0e, 0x3e, 0x2f, 0x83, 0x22, 0x8a, 0x29, 0x17, 0x41, 0x9c, 0xa8, 0x04, 0xf7, 0x17,
	0x02, 0xdb, 0x67, 0x2c, 0xc6, 0x47, 0x50, 0x8b, 0xc2, 0x2e, 0x72, 0x50, 0xcf, 0xf2, 0x6b, 0x51,
	0x88, 0x4f, 0xa0, 0x91, 0x30, 0x2e, 0xa6, 0x51, 0xd8, 0xad, 0xc9, 0x1f, 0xeb, 0x59, 0x78, 0x1e,
	0xe2, 0xb7, 0x00, 0xf3, 0x94, 0x06, 0x82, 0x86, 0xd3, 0x40, 0x74, 0x2d, 0x07, 0xf5, 0x5a, 0x03,
	0xe2, 0xa9, 0x7b, 0x3c, 0x7d, 0x8f, 0x77, 0xa9, 0xef, 0xf1, 0x9b, 0x79, 0xf6, 0x50, 0x64, 0x47,
	0x57, 0x49, 0xa8, 0x8f, 0xda, 0xf7, 0x1f, 0xcd, 0xb3, 0x87, 0xc2, 0xfd, 0x8d, 0xa0, 0x7e, 0x41,
	0xe3, 0x19, 0x4d, 0xb7, 0x55, 0x9a, 0x32, 0x16, 0x1b, 0x95, 0x66, 0xe1, 0xb9, 0x04, 0x56, 0x9c,
	0xa6, 0x19, 0x60, 0x29, 0x20, 0x0b, 0x2b, 0x12, 0xec, 0xc7, 0x4b, 0x38, 0x78, 0x88, 0x84, 0x3f,
	0x08, 0x1a, 0x17, 0x94, 0xf3, 0x60, 0x41, 0x2b, 0x1a, 0x30, 0xd8, 0x33, 0x16, 0xde, 0x4a, 0x01,
	0x4d, 0x5f, 0x7e, 0x9b, 0xba, 0xac, 0x5d, 0xba, 0xec, 0x3b, 0x74, 0x1d, 0x3c, 0x5e, 0x57, 0xfd,
	0x21, 0xba, 0x26, 0x70, 0x38, 0x96, 0x3c, 0x99, 0x8f, 0x7c, 0xfa, 0x03, 0x3b, 0x1b, 0xeb, 0x48,
	0x85, 0xa3, 0xc6, 0xdf, 0x91, 0xed, 0xd6, 0x7a, 0x68, 0xed, 0x21, 0x67, 0xa3, 0xa0, 0x56, 0xca,
	0x50, 0x52, 0xdc, 0x2f, 0x00, 0x9f, 0xa8, 0xd8, 0x27, 0xe3, 0x25, 0x1c, 0x7d, 0x8e, 0xb8, 0x50,
	0x26, 0xe2, 0x39, 0xab, 0x6e, 0x70, 0x99, 0x35, 0xef, 0xf4, 0xfd, 0xac, 0x67, 0x25, 0x56, 0x8e,
	0x5f, 0x40, 0x23, 0x56, 0x51, 0x17, 0x39, 0x56, 0xaf, 0x35, 0xf8, 0xdf, 0x5b, 0x6f, 0xb1, 0xa7,
	0xf2, 0x7c, 0x9d, 0xe1, 0x5e, 0x41, 0x47, 0xf5, 0x2e, 0x07, 0xf6, 0x54, 0xd5, 0x15, 0x74, 0xde,
	0xd3, 0x25, 0xdd, 0x37, 0xed, 0x77, 0x38, 0xd6, 0xd5, 0x4a, 0x1b, 0x67, 0xbc, 0xda, 0xb9, 0xc8,
	0x70, 0xae, 0x53, 0xda, 0xc8, 0x3b, 0xef, 0xb2, 0x76, 0x4a, 0x50, 0x8d, 0x95, 0x37, 0xed, 0x6d,
	0x5e, 0xc3, 0x32, 0x2d, 0xc7, 0x1e, 0xfc, 0x17, 0xe7, 0x61, 0x3e, 0x31, 0x5c, 0x98, 0x98, 0x92,
	0xba, 0xce, 0x71, 0xbf, 0xc2, 0xf1, 0x44, 0xa4, 0x34, 0x88, 0x8d, 0x2e, 0xec, 0xa1, 0xb4, 0xc1,
	0x4f, 0x1b, 0x5a, 0xe3, 0xeb, 0x40, 0x4c, 0x68, 0x7a, 0x13, 0xcd, 0x29, 0x7e, 0x03, 0xb0, 0xd9,
	0x2b, 0xdc, 0x35, 0x6a, 0x2a, 0xac, 0x1b, 0xe9, 0x18, 0x88, 0x4c, 0x7d, 0x05, 0x8d, 0x7c, 0x77,
	0xf0, 0x13, 0x03, 0xdb, 0xec, 0x53, 0xf5, 0xc8, 0x18, 0x5a, 0x86, 0x8d, 0xf1, 0x33, 0x03, 0x2f,
	0x2e, 0x0d, 0xd9, 0x09, 0x71, 0x7c, 0x06, 0x6d, 0xd3, 0xcc, 0x98, 0x54, 0x4a, 0x5e, 0xdb, 0x91,
	0x54, 0x97, 0x02, 0x8f, 0xa0, 0x6d, 0x9a, 0xb6, 0x70, 0xbc, 0xe4, 0x66, 0xf2, 0xb4, 0xf2, 0x34,
	0x7d, 0xc8, 0xfe, 0xf5, 0xf0, 0x47, 0x68, 0x9b, 0xe3, 0x2d, 0x70, 0x94, 0xec, 0x44, 0x76, 0x63,
	0x1c, 0xbf, 0xd3, 0x6f, 0x9a, 0x7e, 0xb0, 0x4f, 0xb7, 0x68, 0xd1, 0xd3, 0x27, 0x5b, 0xfc, 0x82,
	0x47, 0x70, 0x58, 0x70, 0x49, 0x81, 0xa1, 0xec, 0x9f, 0x6d, 0x0c, 0x2f, 0xd1, 0xac, 0x2e, 0xd5,
	0xbd, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x49, 0xa2, 0x85, 0x13, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomReq, opts ...grpc.CallOption) (*Room, error)
	GetRoom(ctx context.Context, in *GetRoomReq, opts ...grpc.CallOption) (*Room, error)
	ListMembers(ctx context.Context, in *ListMembersReq, opts ...grpc.CallOption) (*ListMembersRes, error)
	CreateMember(ctx context.Context, in *CreateMemberReq, opts ...grpc.CallOption) (*Member, error)
	DeleteMember(ctx context.Context, in *DeleteMemberReq, opts ...grpc.CallOption) (*empty.Empty, error)
	ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesRes, error)
	CreateMessage(ctx context.Context, in *CreateMessageReq, opts ...grpc.CallOption) (*Message, error)
	StreamMessage(ctx context.Context, in *StreamMessageReq, opts ...grpc.CallOption) (ChatService_StreamMessageClient, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) CreateRoom(ctx context.Context, in *CreateRoomReq, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/chat_grpc.ChatService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetRoom(ctx context.Context, in *GetRoomReq, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/chat_grpc.ChatService/GetRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListMembers(ctx context.Context, in *ListMembersReq, opts ...grpc.CallOption) (*ListMembersRes, error) {
	out := new(ListMembersRes)
	err := c.cc.Invoke(ctx, "/chat_grpc.ChatService/ListMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateMember(ctx context.Context, in *CreateMemberReq, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/chat_grpc.ChatService/CreateMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteMember(ctx context.Context, in *DeleteMemberReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/chat_grpc.ChatService/DeleteMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesRes, error) {
	out := new(ListMessagesRes)
	err := c.cc.Invoke(ctx, "/chat_grpc.ChatService/ListMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateMessage(ctx context.Context, in *CreateMessageReq, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat_grpc.ChatService/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) StreamMessage(ctx context.Context, in *StreamMessageReq, opts ...grpc.CallOption) (ChatService_StreamMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/chat_grpc.ChatService/StreamMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceStreamMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_StreamMessageClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatServiceStreamMessageClient struct {
	grpc.ClientStream
}

func (x *chatServiceStreamMessageClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	CreateRoom(context.Context, *CreateRoomReq) (*Room, error)
	GetRoom(context.Context, *GetRoomReq) (*Room, error)
	ListMembers(context.Context, *ListMembersReq) (*ListMembersRes, error)
	CreateMember(context.Context, *CreateMemberReq) (*Member, error)
	DeleteMember(context.Context, *DeleteMemberReq) (*empty.Empty, error)
	ListMessages(context.Context, *ListMessagesReq) (*ListMessagesRes, error)
	CreateMessage(context.Context, *CreateMessageReq) (*Message, error)
	StreamMessage(*StreamMessageReq, ChatService_StreamMessageServer) error
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) CreateRoom(ctx context.Context, req *CreateRoomReq) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedChatServiceServer) GetRoom(ctx context.Context, req *GetRoomReq) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (*UnimplementedChatServiceServer) ListMembers(ctx context.Context, req *ListMembersReq) (*ListMembersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembers not implemented")
}
func (*UnimplementedChatServiceServer) CreateMember(ctx context.Context, req *CreateMemberReq) (*Member, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMember not implemented")
}
func (*UnimplementedChatServiceServer) DeleteMember(ctx context.Context, req *DeleteMemberReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMember not implemented")
}
func (*UnimplementedChatServiceServer) ListMessages(ctx context.Context, req *ListMessagesReq) (*ListMessagesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessages not implemented")
}
func (*UnimplementedChatServiceServer) CreateMessage(ctx context.Context, req *CreateMessageReq) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (*UnimplementedChatServiceServer) StreamMessage(req *StreamMessageReq, srv ChatService_StreamMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessage not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_grpc.ChatService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateRoom(ctx, req.(*CreateRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_grpc.ChatService/GetRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetRoom(ctx, req.(*GetRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_grpc.ChatService/ListMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListMembers(ctx, req.(*ListMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_grpc.ChatService/CreateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateMember(ctx, req.(*CreateMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_grpc.ChatService/DeleteMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteMember(ctx, req.(*DeleteMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_grpc.ChatService/ListMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListMessages(ctx, req.(*ListMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_grpc.ChatService/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateMessage(ctx, req.(*CreateMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_StreamMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMessageReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).StreamMessage(m, &chatServiceStreamMessageServer{stream})
}

type ChatService_StreamMessageServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type chatServiceStreamMessageServer struct {
	grpc.ServerStream
}

func (x *chatServiceStreamMessageServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat_grpc.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _ChatService_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _ChatService_GetRoom_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _ChatService_ListMembers_Handler,
		},
		{
			MethodName: "CreateMember",
			Handler:    _ChatService_CreateMember_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _ChatService_DeleteMember_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _ChatService_ListMessages_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _ChatService_CreateMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessage",
			Handler:       _ChatService_StreamMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
