version: '3'
services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile.fresh
    volumes:
      - ./src/.:/app
    depends_on:
      - notification-kvs
      - chat-db
    tty: true
    environment:
      TZ: Asia/Tokyo

  chat-db:
    image: mysql:8.0.17
    volumes:
      - chat-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_DB
      TZ: Asia/Tokyo
    ports:
      - "5306:3306"

  notification-kvs:
    image: redis:5.0.7-alpine3.11
    tty: true
    command: ["--requirepass", "password"]
  
volumes:
  chat-data:
    driver: local
networks:
  default:
    external:
      name: api-gateway_default
